implemented jmztab validation steps

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -41,6 +41,35 @@ jobs:
     - name: Run unit and system tests
       run: |
         pytest --cov=casanovo tests/
+    - name: Set up Java
+      if: runner.os == 'ubuntu-latest' || runner.os == 'macos-13'
+      run: sudo apt-get install -y openjdk-22-jdk
+    - name: Set up Java on Windows
+      if: runner.os == 'windows-latest'
+      uses: actions/setup-java@v3
+      with:
+        distribution: 'zulu'
+        java-version: '22'
+    - name: Run Casanovo sequence
+      run: |
+        casanovo sequence sample_data/sample_preprocessed_spectra.mgf -c tests/ting_config.yaml -o test
+        if [ $? -ne 0 ]; then
+          echo "casanovo command failed with status code $?"
+          exit 1
+        fi
+    - name: Run jmzTabValidator
+      run: |
+        java --jar tests/jmzTabValidator.jar --check inFile=test.mztab > result.log
+        if [ $? -ne 0 ]; then
+          echo "Java command failed with status code $?"
+          exit 1
+        fi
+        grep '^\[Error-' result.log
+        if [ $? -eq 0 ]; then
+          echo "mzTab validation failed:"
+          cat results.log
+          exit 1
+        fi
     - name: Upload coverage to codecov
       uses: codecov/codecov-action@v3
       with:
