status code logic

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -58,14 +58,15 @@ jobs:
     - name: Check validator output
       run: |
         grep '^\[Error-' results.log
-      continue-on-error: true
-    - name: Finish validation
-      run: |
         if [ $? -eq 0 ]; then
           echo "mzTab validation failed:"
           cat results.log
           exit 1
         fi
+        if [ $? -eq 2 ]; then
+          echo "Output results file not found."
+          exit 1
+        fi              
     - name: Upload coverage to codecov
       uses: codecov/codecov-action@v4
       with:
